# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/cloudcraft.js
#####

SDLC_CLOUDCRAFT_JS:=$(DIST)/cloudcraft.js
SDLC_CLOUDCRAFT_JS_ENTRY=$(SRC)/lib/index.mjs
BUILD_TARGETS+=$(SDLC_CLOUDCRAFT_JS)

$(SDLC_CLOUDCRAFT_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_CLOUDCRAFT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/cloudcraft.js
#####
